### ISSUE TITLE
Sample rate

### ISSUE THREAD

**Issue by NikolayTsvetkovv** [AmbiqAI/heartkit#23]
Hello folks,

I have same questions about sample rate of the models.
I saw that in the configuration .json files it set to 200Hz. Let's assume I had sensor with different sample rate from 200Hz.
Is it need to train models, evaluate and export them changing the configuration parameter about sampling rate(in .json files) with my sensor sampling rate?

Also I saw this in the source code:
// print(generate_arm_biquad_sos(10, 30, 200, order=3, var_name="qrsBandPass"))
// print(generate_arm_biquad_sos(0.5, 30, 200, order=3, var_name="ecgBandPass"))
Those function also should be execute with my sensor sample rate. Am I right?

BR, Nikolay

**Comment by apage224** [comment]
Hi Nikolay, 

That is correct- the current set of models are trained directly on 1-lead ECG data w/ specified sampling rate. The models will need to be retrained for different sampling rate -OR- resample your sensor data before running it through the model.

If the models are retrained, the filter coefficients will indeed need to be updated along with configs in constants.h and sample stimulus data in stimulus.h if looking to test on hardware. 

As a heads up, I am working on revamp of HeartKit that will better separate tasks/classes, new models, different feature sets (e.g. HRV metrics, PPG), leverage [PhysioKit](https://github.com/AmbiqAI/physiokit), and add task-specific demos. This is currently under development in branch [feat/physiokit](https://github.com/AmbiqAI/heartkit/tree/feat/physiokit).
